name: yarvolley_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  collection: ^1.19.1
  http: 1.3.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # Регистрация шрифтов
  fonts:
    - family: AppLogoFont
      fonts:
        - asset: assets/fonts/FasterOne-Regular.ttf
    - family: AppCommonFont
      fonts:
        - asset: assets/fonts/AnonymousPro-Regular.ttf
        - asset: assets/fonts/AnonymousPro-Bold.ttf
        - asset: assets/fonts/AnonymousPro-BoldItalic.ttf
        - asset: assets/fonts/AnonymousPro-Italic.ttf